name: Build Kernel

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Android Kernel Builder Action
      uses: mlm-games/simple-kernel-build-action@v1.1.0
      with:
        KERNEL_CLONE_CMD: 'git clone https://github.com/hjiyu1965/android_kernel_zte_ums9620_mifi_f50 -b main ' # PSA: directory and depth=1 are added automatically!
        KERNEL_CONFIG: 'gki_defconfig'
        ARCH: 'arm64'
        TOOLCHAIN_CLONE_CMD: 'git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 ./toolchain/gcc'
        ENABLE_KSU: 'true'
        ENABLE_CCACHE: 'true'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build
        path: 'kernel_source/flashable-anykernel.zip' # Always named flashable-anykernel.zip
